{% set name = "monotonic" %}
{% set version = "1.6" %}
{% set sha256 = "3a55207bcfed53ddd5c5bae174524062935efed17792e9de2ad0205ce9ad63f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - monotonic

about:
  home: https://github.com/atdt/monotonic
  license: Apache 2.0
  license_file: LICENSE
  summary: An implementation of time.monotonic() for Python 2 & Python 3.

extra:
  recipe-maintainers:
    - alimanfoo
    - anguslees
    - sodre
